### ISSUE TITLE
Feedback: First Challenge Submission

### ISSUE THREAD

**Issue by anselb** [daisukiyo/cs-1.3#1]
- In your encode function, I would recommend adding comments to a line like 91, 95 or 96 as there seems to be a lot going on in a single line. You might also want to consider how often you call `int()`, as it seems unnecessary in some places such as line 90 or 91 (both base and int_num have to be numbers to use the modulo operator).
- Your `strings.py` has some good spacing between chunks of code, but I would like to see comments there as well to indicate what each chunk does. 
- In addition, while your use of `find_index` is good in `contains`, `find_index` does not seem to do much for `find_all_indexes` in terms of how much code can be commented out. You might consider using `find_all_indexes` in `find_index`, which could allow you to comment more code out.

**Comment by timkaing** [comment]
Thanks for the feedback:

- Points 1 and 2 have been addressed. 
- Point 3 is technically correct, however I am using the `find_index` to find all indices. I have gone ahead and commented to explain why I could not use `find_all_index` for `find_index`
