### ISSUE TITLE
Feedback: Second Challenge Submission

### ISSUE THREAD

**Issue by anselb** [daisukiyo/cs-1.3#2]
- Nice work on your stacks and queue. I just wanted to remind you that you can use `[-1]` to get the index of the last item of the list, and you should annotate your functions for time complexity.
- In your Set, I think you might have misinterpreted using the hash tables size property. Set still needs its own size property, but the challenge specified doing something like [this](https://stackoverflow.com/questions/17330160/how-does-the-property-decorator-work) with `@property`. For that size method, you might consider changing it to a property, as that's how it was asked for in the challenge, but I don't think it matters that much.
- You have a good start with you set tests, but you should try not to call a method on the underlying structure (hash table) of the set. You have a `size` function you could call, but that appears to have a small bug. You should check if you're calling a function or getting a property.

**Comment by timkaing** [comment]
Thanks for the feedback, I'll definitely look towards using the `@property` in the future

I've cleaned up my sets tests and have noted the use of calling methods

I have also gone ahead and annotated all the time complexities.
